builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "opsworks/php-fpm_exporter:latest"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}"
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "opsworks/php-fpm_exporter:latest"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}"
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: 0hlov3s/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - "opsworks/php-fpm_exporter:latest"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
      - "opsworks/php-fpm_exporter:{{ .Major }}"

changelog:
  filters:
    exclude:
      - "^docs:"

archives:
  - id: default
    format: binary
  - id: targz
    format: tar.gz
