builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "hipages/php-fpm_exporter:latest"
      - "hipages/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "hipages/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
      - "hipages/php-fpm_exporter:{{ .Major }}"
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'

archives:
  - format: binary
